FROM asgpu/notebook:tf-1.10-9d4973b6
SHELL ["/bin/bash", "-c"]
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl htop python-dev python3-dev pkgconf \
        python2.7 python-setuptools python-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER $NB_UID
RUN /usr/bin/pip install wheel tensorflow-gpu==1.10.0